services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./Backend
    restart: unless-stopped
    depends_on:
      - mongo

    env_file:
      - .env.docker

  frontend:
    build:
      context: ./FrontEnd
      args:
        REACT_APP_BACKEND: /api

    restart: unless-stopped
    depends_on:
      - backend

    ports:
      - "8080:80"

    env_file:
      - .env.docker

volumes:
  mongo_data: